### ISSUE TITLE
Feature request: Add custom css (and maybe js?) files

### ISSUE THREAD

**Issue by carlosperate** [google/typedoc-neo-theme#60]
It'd be great if we could include paths to additional css and js files in the `typedoc.json` file to be added to the built output.

This would allow us to tweak the CSS if needed, and add additional js functionality without having to fork the theme and having to maintain that.

**Comment by Fleker** [comment]
I can see how that may be useful, but would that be a feature to bring up to [Typedoc](https://github.com/TypeStrong/typedoc) directly rather than embedded in the theme?

**Comment by carlosperate** [comment]
That's a good point. I haven't really looked at the Typedoc source code or the theming, so I don't really know how it works, but even if the path to the extra files was provided by Typedoc directly, the templates in all the themes would have to include them somehow? Unless Typedoc had a way to inject elements in the DOM independently of the templates?

In other doc generators I've used, this was generally done by the theme, like the readthedocs theme in Sphinx:
- https://github.com/readthedocs/sphinx_rtd_theme/blob/e2b10425ef2fd95d365c78e303af81ecc849040f/sphinx_rtd_theme/layout.html#L33-L35
- https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html

Or with many Jekyll themes:
- https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/head.html#L33-L36
- https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-scripts

**Comment by Fleker** [comment]
I would expect some sort of signal from Typedoc in order to load custom content in the [head](https://github.com/google/typedoc-neo-theme/blob/master/third_party/src/default/layouts/default.hbs) of the page. It could be done in this theme itself, but I would argue that it would make sense to start in Typedoc itself to standardize it. Especially since this feature is not something that would be used in the Actions on Google reference, it would not be something that I may spend much time maintaining and may be buggier than one would want.

**Comment by carlosperate** [comment]
Awesome, thanks Nick!
